version: '3'

services:
  dbms:
    build: .
    command: gunicorn prj.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./:/usr/src/app/
      - ./_static:/usr/src/app/_static
    expose:
      - "8000"
    depends_on:
      - redis

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./_static:/usr/src/app/_static
    depends_on:
      - dbms
      - cropmonitor

  celery_worker:
    build: .
    command: celery -A prj worker --loglevel=info
    volumes:
      - ./:/usr/src/app/
    depends_on:
      - dbms
      - redis

  celery_beat:
    build: .
    command: celery -A prj beat --loglevel=info
    volumes:
      - ./:/usr/src/app/
    depends_on:
      - dbms
      - redis
      - celery_worker

  redis:
    image: redis:latest
    ports:
      - 6379:6379

  cropmonitor:
    build:
      context: .
      dockerfile: Dockerfile
    command: gunicorn -w 4 -k uvicorn.workers.UvicornWorker crop_monitor.app:app --bind 0.0.0.0:7000
    expose:
      - "7000"
    environment:
      - ENVIRONMENT=production
    volumes:
      - .:/app
volumes:
  static_volume:
  media_volume: